language: ruby
rvm:
  - 2.0.0
services:
  - mongodb
bundler_args: --without development --path=~/.bundle
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - gem install bundler bundle_cache
  - bundle_cache_install
after_script:
  - bundle_cache
env:
  global:
  - BUNDLE_ARCHIVE="lumen"
  - AWS_S3_BUCKET="postscript07-bundle_cache"
  - RACK_ENV=test
  - PORT=3000
  - DOMAIN=127.0.0.1:3000
  - SESSION_SECRET=82d320681aeddffb5a77b0d32bd248567042dc4a936695dda6fb614121e26d13
  - secure: hWxfkZDy6gfgKJikEGt0M2Kitua6gLX40wMOwwzdeR8L5PqG6MhzC6QYIY0i2CUWCrLOy8m9WQe+/sgFOrRxnPMUiKDEXbR4lfc4oWgi1qJijSu9NQT22MnDEDK/fAS9yNcsBRI0OjanZozn9yegsN6nX7BqxvMXXepklOZ7uB8=
